### ISSUE TITLE
Compilation errors under newer GCC

### ISSUE THREAD

**Issue by favonia** [leanprover/lean2#5]
Currently, Lean 2 cannot be compiled under newer versions of GCC (like 6.3 or 7). With GCC 7.1.1, it fails with the following error message:
```
[ 59%] Building CXX object frontends/lean/CMakeFiles/lean_frontend.dir/token_table.cpp.o
In file included from /tmp/lean2/src/frontends/lean/token_table.h:10:0,
                 from /tmp/lean2/src/frontends/lean/token_table.cpp:11:
/tmp/lean2/src/util/trie.h: In lambda function:
/tmp/lean2/src/util/trie.h:69:70: error: ‘this’ was not captured for this lambda function
                     new_t1->m_children.insert(k, merge(n1.steal(), c2));
                                                                      ^
/tmp/lean2/src/util/trie.h: In lambda function:
/tmp/lean2/src/util/trie.h:82:38: error: ‘this’ was not captured for this lambda function
                 for_each(f, c, prefix);
                                      ^
make[2]: *** [frontends/lean/CMakeFiles/lean_frontend.dir/build.make:87: frontends/lean/CMakeFiles/lean_frontend.dir/token_table.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:2516: frontends/lean/CMakeFiles/lean_frontend.dir/all] Error 2
make: *** [Makefile:163: all] Error 2
```

**Comment by robertylewis** [comment]
See https://github.com/leanprover/lean/issues/1619 . I imagine the same fixes will apply to Lean 2.

**Comment by favonia** [comment]
@rlewis1988 Thanks. I took a look but am not immediately sure which commits constitute the fix. @leodemoura If you have time, I wonder if you could apply your fixes to Lean 2 as well? I believe it fails to compile for exactly the same reason.

**Comment by fpvandoorn** [comment]
@favonia: I cherry-picked two commits by @leodemoura, so that it now compiles with `g++-6`. There are still some warnings in the build, which I don't know how to fix. I believe these are the relevant commits in Lean 3 fixing these warnings.
https://github.com/leanprover/lean/commit/919cf420ea2609f7951bfa443dc160c0776a8b72
https://github.com/leanprover/lean/commit/603bbe598744fd94a2ba4a8ae23ac01a945d30bc
https://github.com/leanprover/lean/commit/ac1727089449d27a9ce82520cd343378b447fef2
https://github.com/leanprover/lean/commit/24048c42584f12c476377ddda752fe5178271b87
https://github.com/leanprover/lean/commit/56215b36e8b9ef399d9255f05414bb61ef93b4cd

**Comment by favonia** [comment]
I can confirm it compiles with GCC 7.1.1.

**Comment by fpvandoorn** [comment]
I'm closing this. If someone wants to get rid of the warnings, feel free to make a pull request!
